# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Rest-api

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship (0b9c4dfd-d9ca-477a-b279-897de40f2d08)'
    ScriptType: 'FilePath'
    ScriptPath: 'peering.ps1'
    azurePowerShellVersion: 'LatestVersion'